import type { CSSProperties } from "react";

const themeTokens = {
  colorBg: "#fff5fb",
  colorBgAccent: "#ffd9ef",
  colorSurface: "rgba(255, 255, 255, 0.78)",
  colorSurfaceStrong: "rgba(255, 255, 255, 0.9)",
  colorText: "#4f1634",
  colorTextMuted: "#8a5570",
  colorPrimary: "#ff4fa3",
  colorPrimaryStrong: "#e6328d",
  colorSecondary: "#ffb0d7",
  colorGold: "#f5c65a",
  colorGoldSoft: "#ffe6a6",
  colorLike: "#ff4fa3",
  colorPass: "#6f3656",
  shadowCard: "0 28px 80px rgba(172, 28, 102, 0.20)",
  shadowGlow: "0 0 0 1px rgba(255,255,255,0.45), 0 18px 40px rgba(255, 79, 163, 0.25)",
  radiusLg: "32px",
  radiusMd: "22px",
  radiusSm: "16px",
  transitionBase: "220ms ease",
};

export const themeStyleVars: CSSProperties = {
  "--color-bg": themeTokens.colorBg,
  "--color-bg-accent": themeTokens.colorBgAccent,
  "--color-surface": themeTokens.colorSurface,
  "--color-surface-strong": themeTokens.colorSurfaceStrong,
  "--color-text": themeTokens.colorText,
  "--color-text-muted": themeTokens.colorTextMuted,
  "--color-primary": themeTokens.colorPrimary,
  "--color-primary-strong": themeTokens.colorPrimaryStrong,
  "--color-secondary": themeTokens.colorSecondary,
  "--color-gold": themeTokens.colorGold,
  "--color-gold-soft": themeTokens.colorGoldSoft,
  "--color-like": themeTokens.colorLike,
  "--color-pass": themeTokens.colorPass,
  "--shadow-card": themeTokens.shadowCard,
  "--shadow-glow": themeTokens.shadowGlow,
  "--radius-lg": themeTokens.radiusLg,
  "--radius-md": themeTokens.radiusMd,
  "--radius-sm": themeTokens.radiusSm,
  "--transition-base": themeTokens.transitionBase,
} as CSSProperties;
